-- =============================================================================
-- Migration: 0004_clients_vehicles.sql
-- Descrição: Clientes e veículos
-- Referência: docs/ARCHITECTURE.md (seção 7)
-- =============================================================================
--
-- Placeholder da Fase 0. A implementação do schema (tabelas, índices,
-- constraints, RLS e triggers) será feita na Fase 1, conforme o roadmap
-- definido em docs/ARCHITECTURE.md.
