-- =============================================================================
-- Migration: 0008_financial.sql
-- Descrição: Contas a pagar/receber, lançamentos financeiros, fluxo de caixa
-- Referência: docs/ARCHITECTURE.md (seção 7)
-- =============================================================================
--
-- Placeholder da Fase 0. A implementação do schema (tabelas, índices,
-- constraints, RLS e triggers) será feita na Fase 1, conforme o roadmap
-- definido em docs/ARCHITECTURE.md.
